apiVersion: v1
kind: Service
metadata:
  name: supermario-service
spec:
  type: LoadBalancer
  selector:
    app: supermario
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
